[package]
name = "nft-backend"
version = "0.1.0"
authors = ["Florian Fromm <flrn.frmm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.4.2" }
juniper = { git = "https://github.com/graphql-rust/juniper" }
juniper_rocket_async = { git = "https://github.com/graphql-rust/juniper" }

tokio = { version = "1.3", features = ["macros"] }
futures = "0.3.1"


[dev-dependencies]
juniper = { git = "https://github.com/graphql-rust/juniper", features = ["expose-test-schema"] }