version: '3.4'

x-database-credentials: &db-creds
  POSTGRES_DB: "app-db"
  POSTGRES_USER: "app-user"
  POSTGRES_PASSWORD: "verysecurepassword"

services:
  app:
    build:
      context: ".."
      dockerfile: "./cicd/Dockerfile"
    ports:
    - "8080:80"
    environment: 
      POSTGRES_HOST: "postgres-db"
      POSTGRES_PORT: "5432"
      <<: *db-creds
    depends_on:
    - "postgres-db"
  postgres-db:
    image: postgres
    environment: 
      <<: *db-creds
